Update ingress API version
Error:  templates/ingress.yaml: the kind "extensions/v1beta1 Ingress"
is deprecated in favor of "networking.k8s.io/v1beta1 Ingress"